### PR TITLE
Automatically click through the daily SSO prompt

### PR DESCRIPTION
**Pull request by DanielJackoway-at**

### CODE REVIEW

**Comment by DanielJackoway-at** [comment]
I can put this behind an option if you want.

**Comment by banga** [comment]
Nice, thanks!

**Comment by banga** [comment]
I also use https://chrome.google.com/webstore/detail/github-preserve-url-fragm/hnnmkldalhgoloejmgppbbhgbflpeknh to preserve line numbers in the redirect, in case you haven't seen it

**Comment by DanielJackoway-at** [comment]
Oh awesome, just installed!

**Pull request merged**
